{"uuid": "e5eb5640-f697-46a3-8d1d-81f62373e9ee", "children": ["1321a9b5-8e9c-44ba-97b0-fbdfe08aee24"], "befores": [{"name": "_Class__pytest_setup_class", "status": "broken", "statusDetails": {"message": "TypeError: goto_url() missing 1 required positional argument: 'self'\n", "trace": "  File \"E:\\Python\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"E:\\Python\\lib\\site-packages\\_pytest\\fixtures.py\", line 1124, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"E:\\Python\\lib\\site-packages\\_pytest\\fixtures.py\", line 921, in call_fixture_func\n    fixture_result = next(generator)\n  File \"E:\\Python\\lib\\site-packages\\_pytest\\python.py\", line 799, in xunit_setup_class_fixture\n    _call_with_optional_argument(func, self.obj)\n  File \"E:\\Python\\lib\\site-packages\\_pytest\\python.py\", line 732, in _call_with_optional_argument\n    func(arg)\n  File \"E:\\GitTest\\Pytest126mail\\Public\\SetUp_TearDown.py\", line 29, in setup_class\n    self.goto_url(selenium_driver=driver)\n"}, "start": 1608734184952, "stop": 1608734193690}], "start": 1608734184952, "stop": 1608734194280}