{"uuid": "04eb18ac-8c6a-4374-887a-672e30313a1b", "children": ["0a42bdb1-3f2b-4466-a1b4-febf747c4edd"], "befores": [{"name": "_Class__pytest_setup_class", "status": "broken", "statusDetails": {"message": "AttributeError: 'str' object has no attribute 'base_url11'\n", "trace": "  File \"E:\\Python\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"E:\\Python\\lib\\site-packages\\_pytest\\fixtures.py\", line 1124, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"E:\\Python\\lib\\site-packages\\_pytest\\fixtures.py\", line 921, in call_fixture_func\n    fixture_result = next(generator)\n  File \"E:\\Python\\lib\\site-packages\\_pytest\\python.py\", line 799, in xunit_setup_class_fixture\n    _call_with_optional_argument(func, self.obj)\n  File \"E:\\Python\\lib\\site-packages\\_pytest\\python.py\", line 732, in _call_with_optional_argument\n    func(arg)\n  File \"E:\\GitTest\\Pytest126mail\\Public\\SetUp_TearDown.py\", line 29, in setup_class\n    self.goto_url('',self.driver,'')\n  File \"E:\\GitTest\\Pytest126mail\\Public\\Base.py\", line 11, in goto_url\n    self.base_url11 = base_url                             # 和超时时间（timeout）\n"}, "start": 1608737099001, "stop": 1608737099001}], "start": 1608737099001, "stop": 1608737099076}