{"uuid": "14a59fb9-2a04-4aff-b9cb-dd3b77560e0d", "children": ["08106e8e-170e-4c7d-81ec-04a90873de80"], "befores": [{"name": "_Class__pytest_setup_class", "status": "broken", "statusDetails": {"message": "TypeError: aa() missing 1 required positional argument: 'self'\n", "trace": "  File \"E:\\Python\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"E:\\Python\\lib\\site-packages\\_pytest\\fixtures.py\", line 1124, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"E:\\Python\\lib\\site-packages\\_pytest\\fixtures.py\", line 921, in call_fixture_func\n    fixture_result = next(generator)\n  File \"E:\\Python\\lib\\site-packages\\_pytest\\python.py\", line 799, in xunit_setup_class_fixture\n    _call_with_optional_argument(func, self.obj)\n  File \"E:\\Python\\lib\\site-packages\\_pytest\\python.py\", line 732, in _call_with_optional_argument\n    func(arg)\n  File \"E:\\GitTest\\Pytest126mail\\Public\\SetUp_TearDown.py\", line 28, in setup_class\n    self.aa()\n"}, "start": 1608736806334, "stop": 1608736806334}], "start": 1608736806334, "stop": 1608736806395}